services:
  frontend:
    image: ghcr.io/hsheth2/ppa-stats-frontend:latest
    build: frontend
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.ppa-stats-frontend.rule: Host(`ppa-stats.sheth.io`)
      traefik.http.routers.ppa-stats-frontend.tls: true
      traefik.http.routers.ppa-stats-frontend.middlewares: SecureTLS
    networks:
       - traefik
       - default
  lp-proxy:
    image: ghcr.io/hsheth2/ppa-stats-lp-proxy:latest
    build: lp-proxy
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.ppa-stats-lp-proxy.rule: "Host(`ppa-stats.sheth.io`) && PathPrefix(`/lp-api`)"
      traefik.http.routers.ppa-stats-lp-proxy.tls: true
      traefik.http.routers.ppa-stats-lp-proxy.middlewares: SecureTLS
    networks:
       - traefik
       - default

networks:
  traefik:
    external: true
